### ISSUE TITLE
Missing license file

### ISSUE THREAD

**Issue by kinow** [ecmwf/pyflow#2]
Hi,

I think the license file is missing in this repository. I noticed GitHub wasn't showing the license on the sidebar, and then found that the link at the `README.md` was 404'ing.

I was going to send a PR with the license from ecmwf/ecflow, but then I realized that it would probably be better for a PyFlow dev to confirm it first, and then add the correct file.

Thanks
Bruno

**Comment by corentincarton** [comment]
Thanks @kinow. I added the LICENSE file in 3.0.1.

Cheers,
Corentin

**Comment by kinow** [comment]
Thanks @corentincarton !
