### ISSUE TITLE
[question] PyPI package pyflow already taken

### ISSUE THREAD

**Issue by kinow** [ecmwf/pyflow#3]
Hi,

PYPI already has a pyflow package (https://pypi.org/project/pyflow/ & https://github.com/David-OConnor/pyflow), that appears to be actively maintained. Similar names like py-flow are, I believe, discouraged to avoid user confusion & due to typosquatting policies.

The conda package is also already taken… but in this case by another package: https://anaconda.org/conda-forge/pyflow & https://github.com/wonderworks-software/PyFlow

Are there plans to release pyflow to PYPI? If so, would it be under something name like ecmwf-pyflow, or perhaps under another name?

Thanks
-Bruno

p.s.: sorry for sending a question as an issue, let me know if there's a better place (email/discourse/or github discussions in some other repo).

**Comment by corentincarton** [comment]
Hi Bruno,

Thanks for this, we are aware of the issue and we're discussing our options. We'll keep you posted on this thread :)

Cheers,
Corentin

**Comment by floriankrb** [comment]
what about a pip package named "pyflow-workflow-generator"?

**Comment by corentincarton** [comment]
Yes, that's what the plan. That's why we renamed the documentation to pyflow-workflow-generator. I'll push the package to pypi asap.

**Comment by corentincarton** [comment]
Pyflow is available in pypi as pyflow-workflow-generator
