### ISSUE TITLE
Export nested ecflow variables in pf.Script

### ISSUE THREAD

**Issue by kelbling** [ecmwf/pyflow#57]
### Is your feature request related to a problem? Please describe.

When setting up more complex ecflow suite's with pyflow we sometimes like to build up paths (and other variables) with the use of nested ecflow variables, e.g. `A_PATH` = `/root/dir/${MODEL_NAME}/${YMD}`. Unfortunatly, the pyflow.Task only scans the script and not the exported variables for ecflow variables to export and therefore will not export the nested ecflow variables (In the upper example `$MODEL_NAME` and `$YMD`. When using `pf.Script.force_exported()` (what would be more a hack) the variables might get appended after the automatic exports (as they get sorted), leading to undefined variables in the prior variable exports.

Here is a minimal example of the current situation:
```python
import pyflow as pf

loop_script = """
echo ${NESTED_VAR}
"""

with pf.Suite("example_suite"):
    task = pf.Task("example", 
                script=loop_script, 
                host=pf.LocalHost(),
                variables={"NESTED_VAR": "foo_${OTHER_ECFLOW_VAR}", 
                           "OTHER_ECFLOW_VAR": "bar"})

print(f"Defs:\n{task}")

print(f"Script:\n{task.generate_script()}")

```
The variable `$OTHER_ECFLOW_VAR` did not get exported.

### Describe the solution you'd like

It would be great if `pyflow.Task.generate_script()` would, after scanning for ecflow_variables in the script, keep on scanning the exported ecflow_variables for nested ecflow_variables. This should be iterated until no further variables are found with `self.SHELLVAR.findall()`. The nested variables found must then be exported before the variables found in the script.

**Comment by colonesej** [comment]
Hello @kelbling, 
in the `Task` declaration you are in the `ecflow` namespace, let's say. `bash` variables are only meaningful in the script namespace. If you define your task `ecflow` variables value as 

```python
(...)
variables = {
  "NESTED_VAR": "foo_%OTHER_ECFLOW_VAR%",
  "OTHER_ECFLOW_VAR": "bar",
}
```
It should work. `ecflow` will do the variable expansion when creating the job file from the script.

```
  task example
    edit NESTED_VAR 'foo_%OTHER_ECFLOW_VAR%'
    edit OTHER_ECFLOW_VAR 'bar'
    edit ECF_JOB_CMD 'bash -c 'export ECF_PORT=%ECF_PORT%; export ECF_HOST=%ECF_HOST%; export ECF_NAME=%ECF_NAME%; export ECF_PASS=%ECF_PASS%; export ECF_TRYNO=%ECF_TRYNO%; export PATH=/Users/mojp/miniconda3/envs/ecmwf/bin:$PATH; ecflow_client --init="$$" && %ECF_JOB% && ecflow_client --complete || ecflow_client --abort ' 1> %ECF_JOBOUT% 2>&1 &'
    edit ECF_KILL_CMD 'pkill -15 -P %ECF_RID%'
    edit ECF_STATUS_CMD 'true'
    edit ECF_CHECK_CMD 'true'
    edit ECF_OUT '%ECF_HOME%'
    label exec_host "localhost"
```

**Comment by kelbling** [comment]
Hi @colonesej ,
I think there is a missunderstanding. As you can see in the minimal example I added, the ecflow variables are of course in the namespace. The issue is, that the pyflow method `pyflow.Task.generate_script()` scans the `pf.Script` associated with the task and only exports the ecflow variables as bash variables, that get found in the script using  `self.SHELLVAR.findall()`. This does however miss nested ecflow variables, as shown in the minimal example above. If you execute it, you will find, that the `OTHER_ECFLOW_VAR` can be found in the defs, it is missing in the `export`-block in the resulting script however. Here is the output of the minimal example:
```
Defs:
  task example
    edit NESTED_VAR 'foo_${OTHER_ECFLOW_VAR}'
    edit OTHER_ECFLOW_VAR 'bar'
    edit ECF_JOB_CMD 'bash -c 'export ECF_PORT=%ECF_PORT%; export ECF_HOST=%ECF_HOST%; export ECF_NAME=%ECF_NAME%; export ECF_PASS=%ECF_PASS%; export ECF_TRYNO=%ECF_TRYNO%; export PATH=/Users/kelbling/conda/miniconda3/envs/pyflow_lib/bin:$PATH; ecflow_client --init="$$" && %ECF_JOB% && ecflow_client --complete || ecflow_client --abort ' 1> %ECF_JOBOUT% 2>&1 &'
    edit ECF_KILL_CMD 'pkill -15 -P %ECF_RID%'
    edit ECF_STATUS_CMD 'true'
    edit ECF_CHECK_CMD 'true'
    edit ECF_OUT '%ECF_HOME%'
    label exec_host "localhost"

Script:
(['#!/bin/bash', '', 'echo "Running on: $(hostname)" || true', 'set -x # echo script lines as they are executed', 'set -e # stop the shell on first error', 'set -u # fail when using an undefined variable', '', '', 'export ECF_PORT=%ECF_PORT%    # The server port number', 'export ECF_HOST=%ECF_HOST%    # The host name where the server is running', 'export ECF_NAME=%ECF_NAME%    # The name of this current task', 'export ECF_PASS=%ECF_PASS%    # A unique password', 'export ECF_TRYNO=%ECF_TRYNO%  # Current try number of the task', '', 'export NESTED_VAR="%NESTED_VAR%"', '', 'echo "Current working directory: $(pwd)"', '', '%nopp', '', '', 'echo ${NESTED_VAR}', '', '', '%end', ''], [])
```

**Comment by colonesej** [comment]
Hello @kelbling , 
what I tried to say is that this below is not a valid `ecflow` statement, which is what you need in a definition file.
```
edit NESTED_VAR 'foo_${OTHER_ECFLOW_VAR}'
```

If you have instead 

```
edit NESTED_VAR 'foo_%OTHER_ECFLOW_VAR%'
```

during [job creation](https://ecflow.readthedocs.io/en/latest/glossary.html#term-job-creation) `ecflow` will do the variable substitution as expected. In the script you will still have only one export, but the value will be as you expect in the **job** file.

script generated by pyflow will contain:
```
export NESTED_VAR=%NESTED_VAR%
```

the job file, created by ecflow will contain

```
export NESTED_VAR=foo_bar
```

I think you need a running ecflow server and the suite loaded there to check the job creation step, either by submitting a task or checking the 'Edit' tab on ecflow_ui.

**Comment by kelbling** [comment]
Ok I see, thanks for clarifying this.

**Comment by kelbling** [comment]
Aha ok I see. Yeah this makes sense as the export is done outside the `%nopp` block. Ok thanks a lot for clarifying.

**Comment by corentincarton** [comment]
@kelbling indeed, when you deal with ecflow variables, it's best to stick with ecflow variables syntax and only switch to shell variables syntax in the core script.
