### ISSUE TITLE
Use PEP-621, replace setup.py and fix IDE error regarding the version file

### ISSUE THREAD

**Issue by kinow** [ecmwf/pyflow#6]
Hi,

Minor nit-pick. When using an IDE like PyCharm, I get an error in `setup.py` due to the IDE not being smart enough to recognize that the `version.py` is being dynamically loaded.

With [PEP-621](https://peps.python.org/pep-0621/), combining a `pyproject.toml` and `setup.cfg`, it is possible to get rid of `setup.py` without losing any functionality, simplifying the project metadata (you edit an `cfg` file, not a Python file).

**Comment by corentincarton** [comment]
Hi @kinow,

Yes I agree. We are working on a standard packaging for python repositories (we are using pyflow a bit as a guinea pig) and we'll probably use a setup.cfg instead.

Thanks!
Corentin

**Comment by kinow** [comment]
Hi @corentincarton ,

That's great! I have a branch with a work-in-progress. I will submit a draft in case there's anything useful there (but feel free to close that one whenever you want :+1: )

Thanks!
Bruno

**Comment by kinow** [comment]
Closing as #7 was merged :+1: (sorry, forgot to link the PR)
